name: Angular Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
         node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build App
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Droplet
        run: |
          sshpass -p MersedesBenz9999q ssh -o StrictHostKeyChecking=no root@104.131.6.181 "cd /var/www/html/material-report-front && git pull origin master"
